Asp_Net Project/Controllers/SalesController.cs
using Bogus;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Text;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Asp_Net_Project.Controllers
{
    public class SalesController : Controller
    {
        static Bogus.Faker faker = new Faker("en");
        static List<Models.InsertViewModel> OrderList = new List<Models.InsertViewModel>();
        static List<SelectListItem> EmployeeList = new List<SelectListItem>();
        static List<SelectListItem> ShippersList = new List<SelectListItem>();
        static List<SelectListItem> CustomerList = new List<SelectListItem>();
        static List<SelectListItem> ProductsList = new List<SelectListItem>();

        // GET: 查詢頁面
        [HttpGet()]
        public ActionResult Index()
        {
            if (EmployeeList.Count == 0)
            {
                SetShippersList();
                SetEmployeeList();
                SetCustomerList();
                SetProductsList();
            }
            
            ViewBag.EmployeeList = EmployeeList;

            ViewBag.CompanyName = ShippersList;

            return View();
        }

        [HttpPost()]
        public ActionResult index(Models.QueryViewModel QueryData)
        {
            return View();
        }

        //POST: 查詢結果
        [HttpPost()]
        public JsonResult QueryResult(Models.QueryViewModel QueryData)
        {
            DataTable QueryResult = SearchOrdersInfo( QueryData.OrderID
                                                    , QueryData.ContactName
                                                    , QueryData.EmployeeName
                                                    , QueryData.CompanyName
                                                    , QueryData.OrderDate
                                                    , QueryData.ShippedDate
                                                    , QueryData.RequiredDate);

            //將ShippedDate中的null值替換
            for (int i = 0; i < QueryResult.Rows.Count; i++)
            {
                if (QueryResult.Rows[i]["ShippedDate"] == System.DBNull.Value)
                {
                    QueryResult.Rows[i]["ShippedDate"] = DateTime.MinValue;
                }
            }

            ViewBag.QueryResult = QueryResult;

            String result = DataTableToJSON(QueryResult);
            return Json(result);
            //return View();
        }

        //GET: 修改頁面
        [HttpGet()]
        public ActionResult EditOrders(int id)
        {
            if (EmployeeList.Count == 0)
            {
                SetShippersList();
                SetEmployeeList();
                SetShippersList();
                SetProductsList();
            }

            //查詢訂單資料
            DataTable QueryResult = SearchOrderInfo(id);
            DataTable QueryDetalResult = SearchOrderDetailInfo(id);
            

            ViewBag.ContactName = CustomerList;

            ViewBag.EmployeeName = EmployeeList;

            ViewBag.CompanyName = ShippersList;

            ViewBag.OrderInfo = QueryResult;
            ViewBag.OrderDetailInfo = QueryDetalResult;
            return View();
        }

        //POST:修改訂單儲存
        [HttpPost()]
        public ActionResult EditOrders(Models.InsertViewModel UpdateData)
        {
            UpdateOrder(UpdateData);
            
            ViewBag.EmployeeName = EmployeeList;

            ViewBag.CompanyName = ShippersList;
            return RedirectToAction("Index");
        }

        //GET: 新增訂單頁面
        [HttpGet()]
        public ActionResult InsertOrders()
        {
            if (EmployeeList.Count == 0)
            {
                SetShippersList();
                SetEmployeeList();
                SetShippersList();
                SetProductsList();
            }


            ViewBag.ContactName = CustomerList;

            ViewBag.EmployeeName = EmployeeList;

            ViewBag.CompanyName = ShippersList;

            ViewBag.ProductName = ProductsList;

            return View();
        }

        //POST: 新增訂單儲存
        [HttpPost()]
        public ActionResult InsertOrders(Models.InsertViewModel InsertData)
        {
            InsertOrder(InsertData);
            
            ViewBag.EmployeeName = EmployeeList;

            ViewBag.CompanyName = ShippersList;

            return RedirectToAction("Index");
        }

        /// <summary>
        /// 獲取商品細節下拉式選單
        /// </summary>
        /// <param name="id"></param>
        /// <returns>商品細節下拉式選單</returns>
        [HttpGet()]
        public JsonResult GetProductsDetailList()
        {
            return Json(ProductsList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 獲取商品價格
        /// </summary>
        /// <param name="id"></param>
        /// <returns>商品價格</returns>
        [HttpGet()]
        public JsonResult GetProductPrice(int ProductID)
        {
            DataTable result = SearchProductPrice(ProductID);
            return Json(result.Rows[0]["UnitPrice"], JsonRequestBehavior.AllowGet);
        }

        //GET: 刪除訂單動作
        [HttpGet]
        public ActionResult DeleteOrders(int id)
        {
            DeleteOrder(id);

            ViewBag.EmployeeName = EmployeeList;

            ViewBag.CompanyName = ShippersList;

            return View("Index");
        }
        
        //建立負責員工下拉式選單data
        public void SetEmployeeList()
        {
            DataTable EmployeesInfo = SearchEmployeesInfo();
            for (int i = 0; i < EmployeesInfo.Rows.Count; i++)
            {
                string EmployeeName = EmployeesInfo.Rows[i]["FirstName"].ToString() + " " + EmployeesInfo.Rows[i]["LastName"].ToString();
                EmployeeList.Add(new SelectListItem()
                {
                    Text = EmployeeName,
                    Value = EmployeesInfo.Rows[i]["EmployeeID"].ToString(),
                    Selected = false
                });
            }
        }

        //建立運輸公司名稱下拉式選單data
        public void SetShippersList()
        {
            DataTable ShippersInfo = SearchShippersInfo();
            for (int j = 0; j < ShippersInfo.Rows.Count; j++)
            {
                ShippersList.Add(new SelectListItem()
                {
                    Text = ShippersInfo.Rows[j]["CompanyName"].ToString(),
                    Value = ShippersInfo.Rows[j]["ShipperID"].ToString(),
                    Selected = false
                });
            }
        }

        //建立客戶名稱下拉式選單data
        public void SetCustomerList()
        {
            DataTable CustomersInfo = SearchCustomersInfo();
            for (int j = 0; j < CustomersInfo.Rows.Count; j++)
            {
                CustomerList.Add(new SelectListItem()
                {
                    Text = CustomersInfo.Rows[j]["CompanyName"].ToString(),
                    Value = CustomersInfo.Rows[j]["CustomerID"].ToString(),
                    Selected = false
                });
            }
        }

        //建立產品名稱下拉式選單data
        public void SetProductsList()
        {
            DataTable ProductsInfo = SearchProductsInfo();
            for (int j = 0; j < ProductsInfo.Rows.Count; j++)
            {
                ProductsList.Add(new SelectListItem()
                {
                    Text = ProductsInfo.Rows[j]["ProductName"].ToString(),
                    Value = ProductsInfo.Rows[j]["ProductID"].ToString(),
                    Selected = false
                });
            }
        }

        /// <summary>
        /// 取得產品名稱下拉式選單Json
        /// </summary>
        /// <returns>產品名稱下拉式選單Json</returns>
        [HttpPost()]
        public JsonResult GetProductsList()
        {
            DataTable ProductsInfo = SearchProductsInfo();

            String result = DataTableToJSON(ProductsInfo);
            return Json(result);
        }


        /// <summary>
        /// 取得連線字串
        /// </summary>
        /// <returns>連線字串</returns>
        public string GetConnStr()
        {
            return System.Configuration.ConfigurationManager.ConnectionStrings["Default"].ConnectionString;
        }

        /// <summary>
        /// 查詢客戶資料
        /// </summary>
        /// <returns>客戶資料</returns>
        public DataTable SearchCustomersInfo()
        {
            string connStr = this.GetConnStr();

            SqlConnection conn = new SqlConnection(connStr);

            string sql = "Select CustomerID, CompanyName, ContactName " +
                         "From [Sales].[Customers]";

            SqlDataAdapter dataAdapter = new SqlDataAdapter(sql, conn);

            System.Data.DataSet data_result = new System.Data.DataSet();

            dataAdapter.Fill(data_result);

            return data_result.Tables[0];
        }

        /// <summary>
        /// 查詢員工資料
        /// </summary>
        /// <returns>員工資料</returns>
        public DataTable SearchEmployeesInfo()
        {
            string connStr = this.GetConnStr();

            SqlConnection conn = new SqlConnection(connStr);

            string sql = "Select EmployeeID, FirstName, LastName " +
                         "From [HR].[Employees]";

            SqlDataAdapter dataAdapter = new SqlDataAdapter(sql, conn);

            System.Data.DataSet data_result = new System.Data.DataSet();

            dataAdapter.Fill(data_result);

            return data_result.Tables[0];
        }

        /// <summary>
        /// 查詢運輸公司資料
        /// </summary>
        /// <returns>運輸公司資料</returns>
        public DataTable SearchShippersInfo()
        {
            string connStr = this.GetConnStr();

            SqlConnection conn = new SqlConnection(connStr);

            string sql = "Select ShipperID, CompanyName, Phone " +
                         "From [Sales].[Shippers]";

Asp_Net Project/Views/Sales/Index.cshtml
@model Asp_Net_Project.Models.QueryViewModel

@{
    ViewBag.Title = "Index";
}

<h2>訂單查詢頁面</h2>


@using (Html.BeginForm("","Sales", FormMethod.Post, new { id = "postForm"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>QueryViewModel</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">訂單編號</label>
        <div class="col-md-10" style="display: block">
            <input type="text" name="OrderID" value="" class="form-control k-textbox"/>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control k-textbox"})
            @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.EmployeeName, (IEnumerable<SelectListItem>)ViewBag.EmployeeList, "請選擇...", new { @class = "form-control kendoDrop" })
            @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CompanyName, (List<SelectListItem>)ViewBag.CompanyName, "請選擇...", new { @class = "form-control kendoDrop" })
            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">訂購日期</label>
        <div class="col-md-4">
            <input type="date" name="OrderDate" value="" class=" kendoDate" />
        </div>

        <label class="control-label col-md-2">出貨日期</label>
        <div class="col-md-4">
            <input type="date" name="ShippedDate" value="" class="form-control kendoDate" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">需要日期</label>
        <div class="col-md-4">
            <input type="date" name="RequiredDate" value="" class="form-control kendoDate" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="查詢" id="searchBtn" class="btn btn-default" />
            <input type="reset" value="清除" class="btn btn-default" />
            @*<button class="btn btn-success" onclick="location.href='/Sales/InsertOrders'">新增</button>*@
        </div>
    </div>
</div>
}
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <button class="btn btn-success" onclick="location.href='/Sales/InsertOrders'">新增訂單</button>
        </div>
    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<div id="grid"></div>

<style>
    .k-header {
        background-color: #fff;
    }
</style>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $().ready(function () {
        $(".kendoDate").kendoDatePicker();

        $(".kendoDrop").kendoDropDownList();

        $('#searchBtn').on("click",function () {
            
            $.ajax({
                url: "@Url.Action("QueryResult")",
                type: "POST",
                data: $("#postForm").serialize(),
                success: function (result) {
                    result = JSON.parse(result);
                    console.log(result);
                    $("#grid").kendoGrid({
                        dataSource: {
                            data: result,
                            schema: {
                                model: {
                                    fields: {
                                        OrderID: { type: "number" },
                                        CompanyName: { type: "string" },
                                        OrderDate: { type: "date" },
                                        ShippedDate: { type: "date" }
                                    }
                                }
                            },
                            pageSize: 20
                        },
                        groupable: true,
                        sortable: true,
                        pageable: {
                            refresh: true,
                            pageSizes: true,
                            buttonCount: 5
                        },
                        columns: [{
                            field: "OrderID",
                            title: "訂單編號"
                        }, {
                            field: "CompanyName",
                            title: "客戶名稱"
                        }, {
                            field: "OrderDate",
                            title: "訂單日期",
                            template: '#= kendo.toString(OrderDate,"yyyy/MM/dd") #'
                        }, {
                            field: "ShippedDate",
                            title: "發貨日期",
                            template: '#= kendo.toString(ShippedDate,"yyyy/MM/dd") #'
                        }, {
                                command: {
                                    text: "修改",
                                    click: function (e) {
                                        // prevent page scroll position change
                                        e.preventDefault();
                                        // e.target is the DOM element representing the button
                                        var tr = $(e.target).closest("tr"); // get the current table row (tr)
                                        // get the data bound to the current table row
                                        var data = this.dataItem(tr);
                                        window.location = '/Sales/EditOrders?id=' + data.OrderID;
                                    }
                                }, title: " ", width: "180px" 
                        }, {
                                command: {
                                    text: "刪除",
                                    click: function (e) {
                                        // prevent page scroll position change
                                        e.preventDefault();
                                        // e.target is the DOM element representing the button
                                        var tr = $(e.target).closest("tr"); // get the current table row (tr)
                                        // get the data bound to the current table row
                                        var data = this.dataItem(tr);
                                        window.location = '/Sales/DeleteOrders?id=' + data.OrderID;
                                    }
                                }, title: " ", width: "180px"
                        }]
                    });
                }
            });
            return false;
        });
        
    });
</script>

Asp_Net Project/Views/Sales/InsertOrders.cshtml
@model Asp_Net_Project.Models.InsertViewModel

@{
    ViewBag.Title = "InsertOrders";
}

<h2>新增訂單頁面</h2>


@using (Html.BeginForm("InsertOrders", "Sales", FormMethod.Post, new { @id = "insertForm"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>InserViewModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ContactName, (List<SelectListItem>)ViewBag.ContactName, new { @class = "form-control kendoDrop", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeName, (List<SelectListItem>)ViewBag.EmployeeName, new { @class = "form-control kendoDrop", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.OrderDate, new { @type = "date", @class = "form-control kendoDate", required = "required" })
            </div>

            @Html.LabelFor(model => model.RequiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.RequiredDate, new { @type = "date", @class = "form-control kendoDate", required = "required" })
             </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ShippedDate, new { @type = "date", @class = "form-control kendoDate" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyName, (List<SelectListItem>)ViewBag.CompanyName, new { @class = "form-control kendoDrop" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Freight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Freight, new { @type = "number", @class = "form-control k-textbox", required = "required", min = "1"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipCountry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.ShipCountry, new { @class = "form-control k-textbox" })
            </div>

            @Html.LabelFor(model => model.ShipCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.ShipCity, new { @class = "form-control k-textbox" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipRegion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.ShipRegion, new { @class = "form-control k-textbox" })
            </div>

            @Html.LabelFor(model => model.ShipPostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.ShipPostalCode, new { @class = "form-control k-textbox" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ShipAddress, new { @class = "form-control k-textbox" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id ="insertBtn" type="submit" value="存檔" class="btn btn-default" />
            </div>
        </div>

        <a id="addProduct">+新增商品</a>
        <table class="table table-hover text-center" id="productTabel">
            <thead>
                <tr>
                    <th>商品</th>
                    <th>單價</th>
                    <th>數量</th>
                    <th>小計</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        <div id="grid"></div>
    </div>
}

</br>
<div>
    @Html.ActionLink("回前一頁", "Index")
</div>

<style>
    .k-header {
        background-color: #fff;
    }
    /*toolTip 的顏色*/
    .k-widget.k-tooltip {
        border-color: rgb(197, 197, 197);
        background-color: #F20C00;
        color: white;
    }

    /*讓textbox顯示有紅框,因為此方法為預設的行為。*/
    .k-invalid,
    .k-textbox.k-invalid {
        border: 1px solid #ee0101;
    }

    /*加入紅框給kendo ui的元件使用*/
    .UIBorderRed {
        border: 1px solid #ee0101 !important;
    }

    /*預設的errorTip樣式*/
    .errorTip {
        background-color: #ee0101;
        color: #fff;
        float: right;
        font-size: 12px;
        border: 2px solid #ddd;
        -moz-box-shadow: 0 0 6px #000;
        -webkit-box-shadow: 0 0 6px #000;
        padding: 4px 10px 4px 10px;
        border-radius: 6px;
        -webkit-border-radius: 6px;
        position: absolute;
        opacity: 0.87;
        display: none !important;
    }
    /*顯示的errorTip樣式*/
    .errorTipShow {
        background-color: #ee0101;
        color: #fff;
        float: right;
        font-size: 12px;
        border: 2px solid #ddd;
        -moz-box-shadow: 0 0 6px #000;
        -webkit-box-shadow: 0 0 6px #000;
        padding: 4px 10px 4px 10px;
        border-radius: 6px;
        -webkit-border-radius: 6px;
        position: fixed;
        opacity: 0.87;
        display: block !important;
        ;
    }
</style>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $(".kendoDate").kendoDatePicker();

        $(".kendoDrop").kendoDropDownList();
        
        $("#insertForm").kendoValidator();
        var validator = $("#insertForm").kendoValidator().data("kendoValidator");

        var detailIndex = 0;

        $("#grid").kendoGrid({
            dataSource: {
                schema: {
                    model: {
                        fields: {
                            Product: {},
                            UnitPrice: { type: "number" },
                            Qty: { type: "number" },
                            total: { type: "number"}
                        }
                    }
                }
            },
            toolbar: ["create"],
            columns: [
                { field: "Product", title: "商品", width: 200, editor: productDropDownEditor},
                { field: "UnitPrice", title: "單價", format: "{0:c}", width: 200 },
                { field: "Qty", title: "數量", width: 200 },
                { field: "total", title: "小計", width: 200},
                { command: "destroy", title: "&nbsp;", width: 200 }],
            dataBound: function (e) {
                
                $('.k-grid-add').click(function () {
                    var items = e.sender.items();
                    var dataItems = e.sender.dataItems();
                })
            },
            editable: true,
            save: function (data) {
                if (data.values.Qty) {
                    data.model.set("total", data.values.Qty * data.model.UnitPrice);
                }
                else {
                    data.model.set("total", data.model.Qty * data.values.UnitPrice);
                }
            }
        });

        function productDropDownEditor(container, options) {
            var listData = "";

            //如果沒接收過list的資料執行ajax
            if (listData == "") {
                $.ajax({
                    url: "GetProductsList",
                    type: "POST",
                    async: false,
                    success: function (data) {

                        listData = JSON.parse(data);
                    }
                });
            };
            $('<input required name="' + options.field + '"/>')
                .appendTo(container)
                .kendoDropDownList({
                    autoBind: false,
                    dataTextField: "ProductName",
                    dataValueField: "ProductID",
                    dataSource: {
                        data: listData
                    },
                    change: onChange,
                })
        };

        function onChange(e) {
            var grid = e.sender.element.closest(".k-grid").data("kendoGrid");
            var row = e.sender.element.closest("tr");
            var dataItem = grid.dataItem(row);


            $.ajax({
                type: "GET",
                url: "/Sales/GetProductPrice?ProductID=" + dataItem.Product,
                dataType: "json",
                async: false,
                success: function (result) {
                    dataItem.set("UnitPrice", result);

                    var totalValue = dataItem.UnitPrice * dataItem.Qty;

                    dataItem.set("total", totalValue);
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }

        $("#insertBtn").on("click", function () {
            if (validator.validate()) {
                // If the form is valid, the Validator will return true
                save();
            }
        });

        $("#addProduct").on("click", function () {
            $.ajax({
                type: "GET",
                url: "/Sales/GetProductsDetailList",
                dataType: "json",
                success: function (result) {
                    var row = "<tr id='row_" + detailIndex + "'>";
                    // 商品
                    row += "<td>";
                    var productDropList = "<select name='Details[" + detailIndex + "].ProductID' id='product_" + detailIndex + "' class='form-control' onchange='changeProduct(" + detailIndex + ")'>";
                    var list = result;
                    for (var i = 0; i < list.length; i++) {
                        productDropList += "<option value='" + list[i].Value + "'>" + list[i].Text + "</option>"
                    }
                    productDropList += "</select>";
                    row += productDropList;
                    row += "</td>";
                    // 單價
                    row += "<td class='col-xs-2'>";
                    row += "<input type='text' name='Details[" + detailIndex + "].UnitPrice' id='price_" + detailIndex + "' value='0' class='form-control text-right price' onkeyup='changeTotal(" + detailIndex + ");'/>"
                    row += "</td>";
                    // 數量
                    row += "<td class='col-xs-2'>";
                    row += "<input type='number' name='Details[" + detailIndex + "].Qty'  id='num_" + detailIndex + "' class='form-control text-right' value='0' onchange='changeTotal(" + detailIndex + ");'/>"
                    row += "</td>";
                    // 小計
                    row += "<td class='col-xs-2 text-center'>";
                    row += "<span id='total_" + detailIndex + "'>0</span>"
                    row += "</td>";
                    // 按鈕
                    row += "<td class='col-xs-2'>";
                    row += "<button type='button'  class='btn' onclick='removeRow(" + detailIndex + ")'>取消</button>";
                    row += "</td>";

                    row += "</tr>";
                    $('#productTabel').append(row);

                    changeProduct(detailIndex);
                    detailIndex++;
                },
                error: function (err) {
                    console.log(err);
                }
            });
        });

        
    });

    function changeProduct(index) {
        var val = $("#product_" + index).val();

        $.ajax({
            type: "GET",
            url: "/Sales/GetProductPrice?ProductID=" + val,
            dataType: "json",
            success: function (result) {
                $("#price_" + index).val(result);

                changeTotal(index);
            },
            error: function (err) {
                console.log(err);
            }
        });
    }

    function changeTotal(index) {
        var new_price = $("#price_" + index).val();
        var new_num = $("#num_" + index).val();

        if ($("#price_" + index).val() == "") {
            $("#price_" + index).val(0);
            new_price = 0;
        }

        if ($("#num_" + index).val() == "") {
            $("#num_" + index).val(0);
            new_num = 0;
        }

        $("#total_" + index).text(new_price * new_num);
    }

    function removeRow(index) {
        $("#row_" + index).hide();
        $("#product_" + index).val(0);
    }
</script>
<style>
    #productTabel th {
       text-align:center;
    }
</style>